KeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
ObseverPort = 45000
FormulatorPort = 47000
APIPort = 48000
StoreRoot = "./odata"
BackendVersion = 1
RLogHost = ""
RLogPath = ""
UseRLog = false

[ObserverKeyMap]
4JDtZL53jhs7akrTjeaJicnA1ub99vUKkXeySUy6uVZ = "observer0.fletatest.net:45000"
4f52SK2FEc6XzNuQfdQbLmV6o9Dg6UwD5Ajf8NM8XxR = "observer1.fletatest.net:45000"
37mZ3Gt3yW1TU3tt9zPF9hstUHedoXLsfXi8RTPp8Ze = "observer2.fletatest.net:45000"
4c3FinyoBt1BNwv17tHc5gQKVSvu785rM7zq1R58hhL = "observer3.fletatest.net:45000"
3BeyVF3kiCgYZRdPwC5D2C5xddrzmhB8kSaPzjSi59S = "observer4.fletatest.net:45000"
