Port = 41000
APIPort = 48000
GenKeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
Formulator = "THIS_IS_A_ADDRESS_OF_THE_FORMULATOR"
StoreRoot = "./fdata"
BackendVersion = 1
RLogHost = ""
RLogPath = ""
UseRLog = false

[ObserverKeyMap]
4JDtZL53jhs7akrTjeaJicnA1ub99vUKkXeySUy6uVZ = "observer0.fletatest.net:47000"
4f52SK2FEc6XzNuQfdQbLmV6o9Dg6UwD5Ajf8NM8XxR = "observer1.fletatest.net:47000"
37mZ3Gt3yW1TU3tt9zPF9hstUHedoXLsfXi8RTPp8Ze = "observer2.fletatest.net:47000"
4c3FinyoBt1BNwv17tHc5gQKVSvu785rM7zq1R58hhL = "observer3.fletatest.net:47000"
3BeyVF3kiCgYZRdPwC5D2C5xddrzmhB8kSaPzjSi59S = "observer4.fletatest.net:47000"

[SeedNodeMap]
3yTFnJJqx3wCiK2Edk9f9JwdvdkC4DP4T1y8xYztMkf = "seednode1.fletatest.net:41000"
3EjA1hKkfYZ4KL1c4f67CfaNwb9fCqUneiYkyQEhsGi = "seednode2.fletatest.net:41000"
314AUADxjj7nWjeNpR8XEoAh4DdX3ArNHaipPGMFQ4u = "seednode3.fletatest.net:41000"
3n8QNWd7M839ouauhdHvmgmk4NsLj4qGM6tpfoaLNxc = "seednode4.fletatest.net:41000"
